// ReactJS/React-Router_blogger/src/routes/Blog.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import posts from '../api/db.json'
import styles from './blog.module.css'

const Blog = () => {
  const post = posts
  return (
    <div>
      <h1>Blog Posts</h1>
      {post.map((val, index) => (
        <div key={index} className={styles.links}>
          <Link to={`/blog/${val.slug}`}>{val.slug}</Link>
        </div>
      ))}
    </div>
  )
}

export default Blog

// Vue/VueCLI/VueJS_2-CLI-blogger-eg/src/components/Blog.vue
<template>
  <div>
    <h1>Posts Links</h1>
    <ul class="post">
      <li v-for="single in allposts" :key="single.id">
        <router-link :to="{ name: 'template', params: { slug: single.slug } }">
          {{ single.slug }}</router-link
        >
      </li>
    </ul>
  </div>
</template>

<script>
import posts from '@/db/data.json'
export default {
  name: 'BlogPosts',
  created() {
    this.GetPosts()
  },
  data() {
    return {
      allposts: {},
    }
  },
  methods: {
    GetPosts() {
      this.allposts = posts.blog
    },
  },
}
</script>

<style scoped>
ul li {
  padding: 10px;
  list-style: none;
}
</style>
